### ISSUE TITLE
Unclean staging-area exception...

### ISSUE THREAD

**Issue by tristanlins** [bit3/mgpm#2]
```
Exception in thread "main" java.lang.RuntimeException: error: Sie müssen zuerst Ihre aktuelle Staging-Area auflösen.
        at io.bit3.mgpm.cli.CliApplication.git(CliApplication.java:287)
        at io.bit3.mgpm.cli.CliApplication.run(CliApplication.java:102)
        at io.bit3.mgpm.App.runCli(App.java:60)
        at io.bit3.mgpm.App.main(App.java:41)
```

**Comment by tristanlins** [comment]
This should be fixed in the new [9th pre-release](https://github.com/bit3/mgpm/releases/tag/1.0.0-SNAPSHOT.9).
