### ISSUE TITLE
Exception on deleted remote branch

### ISSUE THREAD

**Issue by phortx** [bit3/mgpm#3]
If a remote branch was deleted but still exists locally, mgpm dies with an exception since it can't fetch the ref.

In that case it should probably just ignore that branch. And print a warning so the user may delete the branch manually.

```
 * repository_name           branch_nameException in thread "main" java.lang.RuntimeException: Your configuration specifies to merge with the ref 'branch_name'
from the remote, but no such ref was fetched.
        at io.bit3.mgpm.cli.CliApplication.git(CliApplication.java:287)
        at io.bit3.mgpm.cli.CliApplication.doUpdate(CliApplication.java:196)
        at io.bit3.mgpm.cli.CliApplication.run(CliApplication.java:93)
        at io.bit3.mgpm.App.runCli(App.java:60)
        at io.bit3.mgpm.App.main(App.java:41)
```

**Comment by tristanlins** [comment]
This should be fixed in the new [9th pre-release](https://github.com/bit3/mgpm/releases/tag/1.0.0-SNAPSHOT.9).
